{"errorMessage": "module 'os' has no attribute 'add_dll_directory'", "errorType": "AttributeError", "requestId": "", "stackTrace": ["  File \"/var/lang/lib/python3.10/importlib/__init__.py\", line 126, in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\n", "  File \"<frozen importlib._bootstrap>\", line 1050, in _gcd_import\n", "  File \"<frozen importlib._bootstrap>\", line 1027, in _find_and_load\n", "  File \"<frozen importlib._bootstrap>\", line 1006, in _find_and_load_unlocked\n", "  File \"<frozen importlib._bootstrap>\", line 688, in _load_unlocked\n", "  File \"<frozen importlib._bootstrap_external>\", line 883, in exec_module\n", "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n", "  File \"/var/task/app.py\", line 10, in <module>\n    import pandas as pd\n", "  File \"/var/task/python/pandas/__init__.py\", line 12, in <module>\n    _delvewheel_patch_1_8_2()\n", "  File \"/var/task/python/pandas/__init__.py\", line 9, in _delvewheel_patch_1_8_2\n    os.add_dll_directory(libs_dir)\n"]}